import ContinueWith from "@/components/continueWith";
import { useAuth } from "@/context/authContext";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useState, useEffect, FormEvent } from "react";
import VisibilityIcon from "@mui/icons-material/Visibility";

function Login() {
   const router = useRouter();
   const { currentUser, signInWithEmail } = useAuth();
   const [email, setEmail] = useState("");
   const [error, setError] = useState("");
   const [password, setPassword] = useState("");
   const [showPassword, setShowPassword] = useState(false);

   useEffect(() => {
      if (currentUser) {
         router.replace("/");
      }
   }, [router, currentUser]);

   const loginUser = async (e: FormEvent) => {
      e.preventDefault();

      let signInError = await signInWithEmail(email, password);

      if (signInError) {
         signInError = signInError.split(":")[1].split("(")[0];
         setError(signInError);
         console.log(signInError);
         return;
      }

      setEmail("");
      setPassword("");
   };

   return (
      <div
         className="flex flex-col items-center h-full min-h-screen text-gray-100 bg-lightGray"
         style={{
            backgroundImage:
               "radial-gradient(circle at center, #4a23a9, #5cdde5)",
         }}
      >
         <Head>
            <title>Login | Daya Muneton</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="max-w-[90vw] w-[20rem] my-10">
            <div className="flex flex-col items-center w-full ">
               <div
                  className={`${
                     error === "" ? "hidden" : "flex"
                  } w-full bg-[#ffc0c0]  justify-center`}
               >
                  <p className="p-1 text-sm text-black">{error}</p>
               </div>
               <h1 className="mb-4 text-3xl font-bold">Login</h1>

               <form
                  onSubmit={loginUser}
                  className="flex flex-col items-center w-full"
               >
                  <div className="authInputBox bg-gradient-to-r to-[#5cdde5] from-[#4a23a9]">
                     <input
                        type="text"
                        name="email"
                        required
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                     />
                     <label htmlFor="email">Email:</label>
                  </div>
                  <div className="authInputBox bg-gradient-to-r to-[#5cdde5] from-[#4a23a9]">
                     <input
                        type={`${showPassword ? "text" : "password"}`}
                        name="password"
                        required
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                     />
                     <VisibilityIcon
                        onClick={() => setShowPassword((show) => !show)}
                        className="text-[#aaa] hover:text-[#555] cursor-pointer"
                     />

                     <label htmlFor="password">Password:</label>
                  </div>

                  <div className="flex flex-col items-center w-full mx-auto ">
                     <button
                        type="submit"
                        className="w-full p-2 mt-2 text-white bg-gradient-to-l to-[#5cdde5] from-[#4a23a9] rounded hover:scale-[1.005]"
                     >
                        Continue
                     </button>
                  </div>
               </form>
            </div>

            <div className="flex gap-1 py-4 text-sm">
               <p>{`Don't`} have Have An Account?</p>
               <Link
                  href={`/auth/signup?src=${router.query.src}`}
                  className="text-blue-400 underline"
               >
                  Sign Up
               </Link>
            </div>
            <ContinueWith className="pt-4 mt-2" />
         </div>
      </div>
   );
}

export default Login;
